server:
    port: 8080

spring:
#数据库配置
    datasource:
        name: crm
        url: jdbc:mysql://127.0.0.1:3306/report_export?characterEncoding=utf8&autoReconnect=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
# MyBatis
mybatis:
    #配置类型别名
    typeAliasesPackage: com.gwghk.crm.model
    #dao层接口
    basePackage: com.gwghk.crm.dao
    #配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/mapper/*.xml
    #加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml